[package]
name = "check-latest"
version = "0.0.1"
authors = ["Spenser Black <spenserblack01@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Check if your rust executable is the latest available version"
readme = "README.md"
keywords = ["version", "latest"]
categories = []
repository = "https://github.com/spenserblack/check-latest-rs"
publish = false # You should at least look at this file before you publish

[dependencies]
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
semver = "0.9.0"
serde_json = "1.0"

[badges]
travis-ci = { repository = "spenserblack/check-latest-rs" }
is-it-maintained-issue-resolution = { repository = "spenserblack/check-latest-rs" }
is-it-maintained-open-issues = { repository = "spenserblack/check-latest-rs" }
maintenance = { status = "passively-maintained" }
