name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt -- --check
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo build --verbose --all-features
    - run: cargo test --verbose --all-features
    # NOTE Not testing with only async enabled, due to doc tests that require blocking
    - run: cargo build --verbose --no-default-features --features async
  build-examples:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: cargo build --example basic-usage
      - run: cargo build --example async --no-default-features --features async
